name: Laravel Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testing
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: mbstring, xml, pgsql, pdo_pgsql

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: composer-cache-${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-cache-${{ runner.os }}-

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Set environment variables
        run: |
          echo "APP_KEY=base64:$(php -r 'echo base64_encode(random_bytes(32));')" >> .env.testing
          echo "DB_CONNECTION=pgsql" >> .env.testing
          echo "DB_HOST=localhost" >> .env.testing
          echo "DB_PORT=5432" >> .env.testing
          echo "DB_DATABASE=testing" >> .env.testing
          echo "DB_USERNAME=postgres" >> .env.testing
          echo "DB_PASSWORD=postgres" >> .env.testing
          echo "DB_SCHEMA=testing" >> .env.testing
          echo "DB_SEARCH_PATH=testing,public" >> .env.testing

      - name: Generate application key
        run: php artisan key:generate --ansi

      - name: Run database migrations
        env:
          DB_CONNECTION: pgsql
          DB_HOST: localhost
          DB_PORT: 5432
          DB_DATABASE: testing
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
          DB_SCHEMA: testing
        run: php artisan migrate --force

      - name: Run tests
        env:
          DB_CONNECTION: pgsql
          DB_HOST: localhost
          DB_PORT: 5432
          DB_DATABASE: testing
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
          DB_SCHEMA: testing
        run: php artisan test --parallel --processes=$(nproc) --verbose
